import type { StoredChar } from './types';

export interface ActionDef {
  id: string;
  name: string;
  class: string | null;    // class name, null = feat
  subclass?: string;       // full subclass name from registry
  feat?: string;           // feat name filter (primary)
  featAliases?: string[];  // alternate feat names (e.g. TCE vs XPHB hyphen variants)
  minLevel: number;        // minimum class level (0 for feats)
  maxUses: (classLevel: number, pb: number, abil: StoredChar['abilityScores']) => number;
  resetOn: 'short' | 'long';
  description: string;
  hpPool?: boolean;        // pool drawn in variable HP amounts (e.g. Lay on Hands)
}

export interface ComputedAction {
  id: string;
  name: string;
  current: number;
  max: number;
  resetOn: 'short' | 'long';
  description: string;
  className: string | null;
  hpPool?: boolean;
}

export const ACTION_DEFS: ActionDef[] = [
  // ── Fighter ────────────────────────────────────────────────────────────────
  {
    id: 'second-wind',
    name: 'Second Wind',
    class: 'Fighter',
    minLevel: 1,
    maxUses: (_lvl, pb) => pb,
    resetOn: 'short',
    description: 'Bonus action: regain 1d10 + Fighter level HP.',
  },
  {
    id: 'action-surge',
    name: 'Action Surge',
    class: 'Fighter',
    minLevel: 2,
    maxUses: () => 1,
    resetOn: 'short',
    description: 'Take one additional action on your turn. Not usable on the same turn as a bonus action.',
  },
  {
    id: 'indomitable',
    name: 'Indomitable',
    class: 'Fighter',
    minLevel: 9,
    maxUses: (lvl) => lvl >= 13 ? 2 : 1,
    resetOn: 'long',
    description: 'Reroll a failed saving throw, using the new roll.',
  },
  // ── Battle Master (Fighter subclass) ──────────────────────────────────────
  {
    id: 'superiority-dice',
    name: 'Superiority Dice',
    class: 'Fighter',
    subclass: 'Battle Master',
    minLevel: 3,
    maxUses: (lvl) => lvl >= 11 ? 6 : lvl >= 7 ? 5 : 4,
    resetOn: 'short',
    description: 'Expend a Superiority Die (d8/d10/d12) to fuel combat maneuvers.',
  },
  // ── Druid ──────────────────────────────────────────────────────────────────
  {
    id: 'wild-shape',
    name: 'Wild Shape',
    class: 'Druid',
    minLevel: 2,
    maxUses: () => 2,
    resetOn: 'short',
    description: 'Transform into a beast you have seen. Duration: hours equal to half Druid level.',
  },
  // ── Cleric ─────────────────────────────────────────────────────────────────
  {
    id: 'channel-divinity-cleric',
    name: 'Channel Divinity',
    class: 'Cleric',
    minLevel: 2,
    maxUses: (lvl) => lvl >= 6 ? 2 : 1,
    resetOn: 'short',
    description: 'Channel divine energy to fuel your domain\'s effect (Turn Undead or domain power).',
  },
  // ── Paladin ────────────────────────────────────────────────────────────────
  {
    id: 'divine-sense',
    name: 'Divine Sense',
    class: 'Paladin',
    minLevel: 1,
    maxUses: (_lvl, _pb, abil) => Math.max(1, 1 + Math.floor((abil.cha - 10) / 2)),
    resetOn: 'long',
    description: 'Until end of your next turn, know location of any celestial, fiend, or undead within 60 ft that is not behind total cover.',
  },
  {
    id: 'channel-divinity-paladin',
    name: 'Channel Divinity',
    class: 'Paladin',
    minLevel: 3,
    maxUses: (lvl) => lvl >= 11 ? 2 : 1,
    resetOn: 'short',
    description: 'Channel divine energy to fuel your sacred oath\'s effect.',
  },
  // ── Paladin (BG3) ──────────────────────────────────────────────────────────
  {
    id: 'divine-sense-bg3',
    name: 'Divine Sense',
    class: 'Paladin (BG3)',
    minLevel: 1,
    maxUses: () => 1,
    resetOn: 'short',
    description: 'Bonus action: gain Advantage on attack rolls against celestials, fiends, and undead until the end of your next turn.',
  },
  {
    id: 'lay-on-hands-bg3',
    name: 'Lay on Hands',
    class: 'Paladin (BG3)',
    minLevel: 1,
    maxUses: (lvl) => lvl >= 10 ? 5 : lvl >= 4 ? 4 : 3,
    resetOn: 'long',
    description: 'Spend a charge to heal a creature you touch or cure all diseases and poisons. Charges: 3 (lvl 1–3), 4 (lvl 4–9), 5 (lvl 10+).',
  },
  {
    id: 'channel-oath',
    name: 'Channel Oath',
    class: 'Paladin (BG3)',
    minLevel: 1,
    maxUses: () => 1,
    resetOn: 'short',
    description: 'Expend a Channel Oath charge to activate one of your sacred oath\'s channel abilities (abilities unlock at level 3).',
  },
  // ── Wizard ─────────────────────────────────────────────────────────────────
  {
    id: 'arcane-recovery',
    name: 'Arcane Recovery',
    class: 'Wizard',
    minLevel: 1,
    maxUses: () => 1,
    resetOn: 'long',
    description: 'Once per day during a short rest, recover spell slots totaling half your Wizard level (rounded up, max slot level 5).',
  },
  // ── Ranger ─────────────────────────────────────────────────────────────────
  {
    id: 'favored-foe',
    name: 'Favored Foe',
    class: 'Ranger',
    minLevel: 1,
    maxUses: (_lvl, pb) => pb,
    resetOn: 'long',
    description: 'When you hit a creature, mark it as your favored enemy (concentration). Add 1d4 to weapon damage against it on first hit each turn.',
  },
  // ── Feats — short rest ─────────────────────────────────────────────────────
  {
    id: 'lucky',
    name: 'Lucky',
    class: null,
    feat: 'Lucky',
    minLevel: 0,
    maxUses: () => 3,
    resetOn: 'long',
    description: 'Spend a luck point to reroll any attack roll, ability check, or saving throw you make, or to impose a reroll on an attacker.',
  },
  {
    id: 'fade-away',
    name: 'Fade Away',
    class: null,
    feat: 'Fade Away',
    minLevel: 0,
    maxUses: () => 1,
    resetOn: 'short',
    description: 'Reaction: when you take damage, become invisible until end of your next turn or until you attack/deal damage/force a save.',
  },
  {
    id: 'second-chance',
    name: 'Second Chance',
    class: null,
    feat: 'Second Chance',
    minLevel: 0,
    maxUses: () => 1,
    resetOn: 'short',
    description: 'Reaction: when a creature you can see hits you with an attack, force it to reroll. Also resets when you roll initiative.',
  },
  {
    id: 'mage-slayer-guarded-mind',
    name: 'Guarded Mind',
    class: null,
    feat: 'Mage Slayer',
    minLevel: 0,
    maxUses: () => 1,
    resetOn: 'short',
    description: 'If you fail an INT, WIS, or CHA saving throw, you can cause yourself to succeed instead.',
  },
  {
    id: 'inspiring-leader',
    name: 'Inspiring Leader',
    class: null,
    feat: 'Inspiring Leader',
    minLevel: 0,
    maxUses: () => 1,
    resetOn: 'short',
    description: 'After a short or long rest performance: up to 6 allies within 30 ft gain temporary HP equal to your character level + ability modifier.',
  },
  {
    id: 'musician-song',
    name: 'Encouraging Song',
    class: null,
    feat: 'Musician',
    minLevel: 0,
    maxUses: () => 1,
    resetOn: 'short',
    description: 'After a short or long rest, play an instrument to give Heroic Inspiration to a number of allies equal to your proficiency bonus.',
  },
  {
    id: 'orcish-fury',
    name: 'Orcish Fury',
    class: null,
    feat: 'Orcish Fury',
    minLevel: 0,
    maxUses: () => 1,
    resetOn: 'short',
    description: 'When you hit with a simple or martial weapon, roll one of the weapon\'s damage dice again and add it as extra damage.',
  },
  {
    id: 'martial-adept-die',
    name: 'Martial Adept Die',
    class: null,
    feat: 'Martial Adept',
    minLevel: 0,
    maxUses: () => 1,
    resetOn: 'short',
    description: 'One superiority die (d6) to fuel Battle Master maneuvers. Expend to use a learned maneuver.',
  },
  // ── Feats — long rest ──────────────────────────────────────────────────────
  {
    id: 'magic-initiate-spell',
    name: 'Magic Initiate',
    class: null,
    feat: 'Magic Initiate',
    minLevel: 0,
    maxUses: () => 1,
    resetOn: 'long',
    description: 'Cast your chosen 1st-level spell once without expending a spell slot.',
  },
  {
    id: 'fey-touched-spells',
    name: 'Fey-Touched',
    class: null,
    feat: 'Fey-Touched',
    featAliases: ['Fey Touched'],
    minLevel: 0,
    maxUses: () => 2,
    resetOn: 'long',
    description: 'Cast Misty Step and your chosen Divination/Enchantment spell (each once) without expending a spell slot.',
  },
  {
    id: 'shadow-touched-spells',
    name: 'Shadow-Touched',
    class: null,
    feat: 'Shadow-Touched',
    featAliases: ['Shadow Touched'],
    minLevel: 0,
    maxUses: () => 2,
    resetOn: 'long',
    description: 'Cast Invisibility and your chosen Illusion/Necromancy spell (each once) without expending a spell slot.',
  },
  {
    id: 'telepathic-detect-thoughts',
    name: 'Detect Thoughts',
    class: null,
    feat: 'Telepathic',
    minLevel: 0,
    maxUses: () => 1,
    resetOn: 'long',
    description: 'Cast Detect Thoughts without a spell slot or components.',
  },
  {
    id: 'drow-high-magic-spells',
    name: 'Drow High Magic',
    class: null,
    feat: 'Drow High Magic',
    minLevel: 0,
    maxUses: () => 2,
    resetOn: 'long',
    description: 'Cast Levitate and Dispel Magic (each once) without expending a spell slot. Charisma is the spellcasting ability.',
  },
  {
    id: 'wood-elf-magic-spells',
    name: 'Wood Elf Magic',
    class: null,
    feat: 'Wood Elf Magic',
    minLevel: 0,
    maxUses: () => 2,
    resetOn: 'long',
    description: 'Cast Longstrider and Pass Without Trace (each once) without expending a spell slot. Wisdom is the spellcasting ability.',
  },
  {
    id: 'chromatic-infusion',
    name: 'Chromatic Infusion',
    class: null,
    feat: 'Gift of the Chromatic Dragon',
    minLevel: 0,
    maxUses: () => 1,
    resetOn: 'long',
    description: 'Bonus action: touch a weapon to infuse it with acid/cold/fire/lightning/poison damage (+1d4) for 1 minute.',
  },
  {
    id: 'reactive-resistance',
    name: 'Reactive Resistance',
    class: null,
    feat: 'Gift of the Chromatic Dragon',
    minLevel: 0,
    maxUses: (_lvl, pb) => pb,
    resetOn: 'long',
    description: 'Reaction: when you take acid/cold/fire/lightning/poison damage, gain resistance to that instance of damage.',
  },
  {
    id: 'telekinetic-reprisal',
    name: 'Telekinetic Reprisal',
    class: null,
    feat: 'Gift of the Gem Dragon',
    minLevel: 0,
    maxUses: (_lvl, pb) => pb,
    resetOn: 'long',
    description: 'Reaction: when a creature within 10 ft damages you, force a STR save or deal 2d8 force and push it 10 ft.',
  },
  {
    id: 'draconic-healing',
    name: 'Draconic Healing',
    class: null,
    feat: 'Gift of the Metallic Dragon',
    minLevel: 0,
    maxUses: () => 1,
    resetOn: 'long',
    description: 'Cast Cure Wounds once without expending a spell slot.',
  },
  {
    id: 'protective-wings',
    name: 'Protective Wings',
    class: null,
    feat: 'Gift of the Metallic Dragon',
    minLevel: 0,
    maxUses: (_lvl, pb) => pb,
    resetOn: 'long',
    description: 'Reaction: when you or a creature within 5 ft is hit by an attack, manifest spectral wings to grant a bonus to AC against that attack.',
  },

  // ── Paladin (PHB) — Lay on Hands ──────────────────────────────────────────
  {
    id: 'lay-on-hands',
    name: 'Lay on Hands',
    class: 'Paladin',
    minLevel: 1,
    maxUses: (lvl) => lvl * 5,
    resetOn: 'long',
    description: 'Restore HP (draw from pool) or expend 5 HP to cure a disease/poison on a touched creature. Pool = 5 × Paladin level.',
    hpPool: true,
  },

  // ── Ranger (PHB) — base features ──────────────────────────────────────────
  {
    id: 'natures-veil',
    name: "Nature's Veil",
    class: 'Ranger',
    minLevel: 10,
    maxUses: (_lvl, pb) => pb,
    resetOn: 'long',
    description: 'Bonus action: become invisible until the start of your next turn.',
  },
  {
    id: 'tireless',
    name: 'Tireless',
    class: 'Ranger',
    minLevel: 10,
    maxUses: (_lvl, _pb, abil) => Math.max(1, Math.floor((abil.wis - 10) / 2)),
    resetOn: 'long',
    description: 'As an action, give yourself temporary HP equal to 1d8 + WIS modifier. Also: exhaustion gained reduces by 1 when you finish a short rest.',
  },

  // ── Ranger (PHB) subclasses ────────────────────────────────────────────────
  {
    id: 'detect-portal',
    name: 'Detect Portal',
    class: 'Ranger',
    subclass: 'Horizon Walker',
    minLevel: 3,
    maxUses: () => 1,
    resetOn: 'short',
    description: 'Detect the distance and direction of the nearest planar portal within 1 mile.',
  },
  {
    id: 'ethereal-step',
    name: 'Ethereal Step',
    class: 'Ranger',
    subclass: 'Horizon Walker',
    minLevel: 7,
    maxUses: () => 1,
    resetOn: 'short',
    description: 'Bonus action: become ethereal until the end of your turn (pass through objects, ignore difficult terrain).',
  },
  {
    id: 'hunters-sense',
    name: "Hunter's Sense",
    class: 'Ranger',
    subclass: 'Monster Slayer',
    minLevel: 3,
    maxUses: (_lvl, _pb, abil) => Math.max(1, Math.floor((abil.wis - 10) / 2)),
    resetOn: 'long',
    description: 'Action: learn immunities, resistances, and vulnerabilities of one creature within 60 ft.',
  },
  {
    id: 'slayers-prey',
    name: "Slayer's Prey",
    class: 'Ranger',
    subclass: 'Monster Slayer',
    minLevel: 3,
    maxUses: () => 1,
    resetOn: 'short',
    description: 'Bonus action: mark one creature as your prey. First hit each turn deals +1d6 damage.',
  },
  {
    id: 'otherworldly-glamour',
    name: 'Otherworldly Glamour',
    class: 'Ranger',
    subclass: 'Fey Wanderer',
    minLevel: 3,
    maxUses: (_lvl, _pb, abil) => Math.max(1, Math.floor((abil.wis - 10) / 2)),
    resetOn: 'long',
    description: 'Add WIS modifier to Charisma checks. When you make a Charisma check, use this charge to add WIS modifier again.',
  },
  {
    id: 'writhing-tide',
    name: 'Writhing Tide',
    class: 'Ranger',
    subclass: 'Swarmkeeper',
    minLevel: 7,
    maxUses: (_lvl, pb) => pb,
    resetOn: 'long',
    description: 'Bonus action: the swarm carries you up to 10 ft and you can fly up to 10 ft without provoking opportunity attacks.',
  },

  // ── Barbarian subclasses ───────────────────────────────────────────────────
  {
    id: 'magic-awareness',
    name: 'Magic Awareness',
    class: 'Barbarian',
    subclass: 'Wild Magic',
    minLevel: 3,
    maxUses: (_lvl, pb) => pb,
    resetOn: 'long',
    description: 'Action: sense active spells and magic items within 60 ft until the end of your next turn.',
  },
  {
    id: 'bolstering-magic',
    name: 'Bolstering Magic',
    class: 'Barbarian',
    subclass: 'Wild Magic',
    minLevel: 6,
    maxUses: (_lvl, pb) => pb,
    resetOn: 'long',
    description: 'Touch a creature to give it a d3 bonus to attack rolls and ability checks for 10 min, or let it recover one expended spell slot (max level = 1d3).',
  },
  {
    id: 'infectious-fury',
    name: 'Infectious Fury',
    class: 'Barbarian',
    subclass: 'Beast',
    minLevel: 10,
    maxUses: (_lvl, _pb, abil) => Math.max(1, Math.floor((abil.con - 10) / 2)),
    resetOn: 'long',
    description: 'When you hit a creature while raging, it must succeed on a WIS save (DC 8 + PB + CON mod) or attack another creature or take 2d12 psychic damage.',
  },

  // ── Bard subclasses ────────────────────────────────────────────────────────
  {
    id: 'words-of-terror',
    name: 'Words of Terror',
    class: 'Bard',
    subclass: 'College of Whispers',
    minLevel: 3,
    maxUses: () => 1,
    resetOn: 'short',
    description: 'Spend 1 minute in conversation to frighten a humanoid for 1 hour (WIS save). On success, it doesn\'t know you tried.',
  },
  {
    id: 'mantle-of-whispers',
    name: 'Mantle of Whispers',
    class: 'Bard',
    subclass: 'College of Whispers',
    minLevel: 6,
    maxUses: () => 1,
    resetOn: 'short',
    description: 'Reaction: when a humanoid dies within 30 ft, capture its shadow. Expend to assume its appearance and memories for 1 hour.',
  },
  {
    id: 'tales-from-beyond',
    name: 'Tales from Beyond',
    class: 'Bard',
    subclass: 'College of Spirits',
    minLevel: 3,
    maxUses: (_lvl, _pb, abil) => Math.max(1, Math.floor((abil.cha - 10) / 2)),
    resetOn: 'short',
    description: 'Expend a use of Bardic Inspiration to roll on the Spirit Tales table and cast a spell or gain an effect from beyond.',
  },
  {
    id: 'performance-of-creation',
    name: 'Performance of Creation',
    class: 'Bard',
    subclass: 'College of Creation',
    minLevel: 3,
    maxUses: (_lvl, pb) => pb,
    resetOn: 'long',
    description: 'Action: conjure one nonmagical item worth ≤ 20 × Bard level gp that fits in a 5-ft cube. Lasts 1 hour.',
  },
  {
    id: 'enthralling-performance',
    name: 'Enthralling Performance',
    class: 'Bard',
    subclass: 'College of Glamour',
    minLevel: 3,
    maxUses: (_lvl, _pb, abil) => Math.max(1, Math.floor((abil.cha - 10) / 2)),
    resetOn: 'short',
    description: 'Perform for 1 minute: up to 5 humanoids who heard it are charmed for 1 hour (WIS save) and regard you as a wondrous performer.',
  },

  // ── Cleric subclasses ──────────────────────────────────────────────────────
  {
    id: 'warding-flare',
    name: 'Warding Flare',
    class: 'Cleric',
    subclass: 'Light Domain',
    minLevel: 1,
    maxUses: (_lvl, _pb, abil) => Math.max(1, Math.floor((abil.wis - 10) / 2)),
    resetOn: 'long',
    description: 'Reaction: when attacked, impose disadvantage on that attack roll by interposing holy light.',
  },
  {
    id: 'wrath-of-the-storm',
    name: 'Wrath of the Storm',
    class: 'Cleric',
    subclass: 'Tempest Domain',
    minLevel: 1,
    maxUses: (_lvl, _pb, abil) => Math.max(1, Math.floor((abil.wis - 10) / 2)),
    resetOn: 'long',
    description: 'Reaction: when a creature within 5 ft hits you, deal 2d8 lightning or thunder damage (DEX save for half).',
  },
  {
    id: 'war-priest',
    name: 'War Priest',
    class: 'Cleric',
    subclass: 'War Domain',
    minLevel: 1,
    maxUses: (_lvl, _pb, abil) => Math.max(1, Math.floor((abil.wis - 10) / 2)),
    resetOn: 'long',
    description: 'Bonus action: when you use the Attack action, make one weapon attack as a bonus action.',
  },
  {
    id: 'eyes-of-the-grave',
    name: 'Eyes of the Grave',
    class: 'Cleric',
    subclass: 'Grave Domain',
    minLevel: 1,
    maxUses: (_lvl, _pb, abil) => Math.max(1, Math.floor((abil.wis - 10) / 2)),
    resetOn: 'long',
    description: 'Action: detect undead creatures within 60 ft (not behind total cover) until end of your next turn.',
  },
  {
    id: 'sentinel-at-deaths-door',
    name: "Sentinel at Death's Door",
    class: 'Cleric',
    subclass: 'Grave Domain',
    minLevel: 6,
    maxUses: (_lvl, _pb, abil) => Math.max(1, Math.floor((abil.wis - 10) / 2)),
    resetOn: 'long',
    description: "Reaction: negate a critical hit on you or a creature you can see within 30 ft, turning it into a normal hit.",
  },
  {
    id: 'steps-of-night',
    name: 'Steps of Night',
    class: 'Cleric',
    subclass: 'Twilight Domain',
    minLevel: 6,
    maxUses: (_lvl, pb) => pb,
    resetOn: 'long',
    description: 'Bonus action (in dim light or darkness): fly up to your speed until end of the turn.',
  },
  {
    id: 'embodiment-of-the-law',
    name: 'Embodiment of the Law',
    class: 'Cleric',
    subclass: 'Order Domain',
    minLevel: 6,
    maxUses: (_lvl, _pb, abil) => Math.max(1, Math.floor((abil.wis - 10) / 2)),
    resetOn: 'long',
    description: 'When you cast an enchantment spell of 1st level or higher, cast it as a bonus action.',
  },

  // ── Druid subclasses ───────────────────────────────────────────────────────
  {
    id: 'natural-recovery',
    name: 'Natural Recovery',
    class: 'Druid',
    subclass: 'Circle of the Land',
    minLevel: 2,
    maxUses: () => 1,
    resetOn: 'long',
    description: 'During a short rest, recover expended spell slots totaling half your Druid level (rounded up, max slot level 5).',
  },
  {
    id: 'spirit-totem',
    name: 'Spirit Totem',
    class: 'Druid',
    subclass: 'Circle of the Shepherd',
    minLevel: 2,
    maxUses: () => 1,
    resetOn: 'short',
    description: 'Bonus action: summon a spirit totem (bear/hawk/unicorn) within 60 ft. All allies in 30 ft gain the spirit\'s benefit while it persists.',
  },
  {
    id: 'star-map',
    name: 'Star Map (Spells)',
    class: 'Druid',
    subclass: 'Circle of Stars',
    minLevel: 2,
    maxUses: (_lvl, pb) => pb,
    resetOn: 'long',
    description: 'Cast Guidance or Guiding Bolt without expending a spell slot (once per use).',
  },

  // ── Fighter subclasses ─────────────────────────────────────────────────────
  {
    id: 'arcane-shot',
    name: 'Arcane Shot',
    class: 'Fighter',
    subclass: 'Arcane Archer',
    minLevel: 3,
    maxUses: () => 2,
    resetOn: 'short',
    description: 'When you hit with a shortbow/longbow, apply one of your Arcane Shot options (Banishing Arrow, Bursting Arrow, etc.).',
  },
  {
    id: 'unwavering-mark',
    name: 'Unwavering Mark',
    class: 'Fighter',
    subclass: 'Cavalier',
    minLevel: 3,
    maxUses: (_lvl, _pb, abil) => Math.max(1, Math.floor((abil.str - 10) / 2)),
    resetOn: 'long',
    description: 'When you hit a creature, mark it until end of your next turn. Marked creature has disadvantage attacking non-you targets. Bonus action: make one melee attack against a marked creature that attacked an ally.',
  },
  {
    id: 'warding-maneuver',
    name: 'Warding Maneuver',
    class: 'Fighter',
    subclass: 'Cavalier',
    minLevel: 7,
    maxUses: (_lvl, _pb, abil) => Math.max(1, Math.floor((abil.con - 10) / 2)),
    resetOn: 'long',
    description: 'Reaction: when you or a mounted creature within 5 ft is hit, add 1d8 to the target\'s AC for that attack (may cause a miss).',
  },
  {
    id: 'giants-might',
    name: "Giant's Might",
    class: 'Fighter',
    subclass: 'Rune Knight',
    minLevel: 3,
    maxUses: (_lvl, pb) => pb,
    resetOn: 'long',
    description: 'Bonus action: grow to Large size (or larger at higher levels) for 1 minute. Advantage on STR checks and saves, +1d6 damage on weapon hits.',
  },
  {
    id: 'runic-shield',
    name: 'Runic Shield',
    class: 'Fighter',
    subclass: 'Rune Knight',
    minLevel: 7,
    maxUses: (_lvl, pb) => pb,
    resetOn: 'long',
    description: 'Reaction: when a creature you can see is hit by an attack, force the attacker to reroll and use the lower result.',
  },
  {
    id: 'unleash-incarnation',
    name: 'Unleash Incarnation',
    class: 'Fighter',
    subclass: 'Echo Knight',
    minLevel: 3,
    maxUses: (_lvl, _pb, abil) => Math.max(1, Math.floor((abil.con - 10) / 2)),
    resetOn: 'long',
    description: 'When you take the Attack action, your echo can make one melee attack as a bonus action.',
  },

  // ── Monk subclasses ────────────────────────────────────────────────────────
  {
    id: 'touch-of-death',
    name: 'Touch of Death',
    class: 'Monk',
    subclass: 'Way of the Long Death',
    minLevel: 3,
    maxUses: (_lvl, _pb, abil) => Math.max(1, Math.floor((abil.wis - 10) / 2)),
    resetOn: 'long',
    description: 'When a creature within 5 ft of you dies, gain temporary HP equal to your Monk level + WIS modifier.',
  },
  {
    id: 'hand-of-harm',
    name: 'Hand of Harm',
    class: 'Monk',
    subclass: 'Way of Mercy',
    minLevel: 3,
    maxUses: (_lvl, _pb, abil) => Math.max(1, Math.floor((abil.wis - 10) / 2)),
    resetOn: 'long',
    description: 'When you hit with an unarmed strike, spend 1 ki point to add necrotic damage (1d6 + WIS mod) and possibly inflict Poisoned.',
  },
  {
    id: 'hand-of-healing',
    name: 'Hand of Healing',
    class: 'Monk',
    subclass: 'Way of Mercy',
    minLevel: 3,
    maxUses: (_lvl, _pb, abil) => Math.max(1, Math.floor((abil.wis - 10) / 2)),
    resetOn: 'long',
    description: 'Action: spend 1 ki point to restore HP to a touched creature equal to 1d6 + WIS modifier and end one disease or condition on it.',
  },
  {
    id: 'wholeness-of-body',
    name: 'Wholeness of Body',
    class: 'Monk',
    subclass: 'Way of the Open Hand',
    minLevel: 6,
    maxUses: (_lvl, _pb, abil) => Math.max(1, Math.floor((abil.wis - 10) / 2)),
    resetOn: 'long',
    description: 'Action: regain HP equal to 3 × Monk level.',
  },

  // ── Sorcerer subclasses ────────────────────────────────────────────────────
  {
    id: 'tides-of-chaos',
    name: 'Tides of Chaos',
    class: 'Sorcerer',
    subclass: 'Wild Magic',
    minLevel: 1,
    maxUses: () => 1,
    resetOn: 'long',
    description: 'Gain advantage on one attack roll, ability check, or saving throw. The DM may trigger a Wild Magic Surge to restore this use.',
  },
  {
    id: 'favored-by-the-gods',
    name: 'Favored by the Gods',
    class: 'Sorcerer',
    subclass: 'Divine Soul',
    minLevel: 1,
    maxUses: () => 1,
    resetOn: 'short',
    description: 'When you fail a saving throw or miss with an attack, add 2d4 to the total (potentially turning a failure into a success).',
  },
  {
    id: 'restore-balance',
    name: 'Restore Balance',
    class: 'Sorcerer',
    subclass: 'Clockwork Soul',
    minLevel: 1,
    maxUses: (_lvl, pb) => pb,
    resetOn: 'long',
    description: 'Reaction: when a creature you can see is about to roll with advantage or disadvantage, cancel it.',
  },

  // ── Warlock subclasses ─────────────────────────────────────────────────────
  {
    id: 'fey-presence',
    name: 'Fey Presence',
    class: 'Warlock',
    subclass: 'The Archfey',
    minLevel: 1,
    maxUses: () => 1,
    resetOn: 'short',
    description: 'Action: each creature in a 10-ft cube originating from you must succeed on a WIS save or be charmed or frightened (your choice) until end of your next turn.',
  },
  {
    id: 'misty-escape',
    name: 'Misty Escape',
    class: 'Warlock',
    subclass: 'The Archfey',
    minLevel: 6,
    maxUses: () => 1,
    resetOn: 'short',
    description: 'Reaction: when you take damage, teleport up to 60 ft to an unoccupied space you can see, then become invisible until end of your next turn or until you attack/cast.',
  },
  {
    id: 'hexblades-curse',
    name: "Hexblade's Curse",
    class: 'Warlock',
    subclass: 'The Hexblade',
    minLevel: 1,
    maxUses: () => 1,
    resetOn: 'short',
    description: 'Bonus action: curse one creature you can see within 30 ft for 1 minute. +PB damage vs it, crit on 19–20, regain HP = level + CHA on kill.',
  },
  {
    id: 'healing-light',
    name: 'Healing Light',
    class: 'Warlock',
    subclass: 'The Celestial',
    minLevel: 1,
    maxUses: (_lvl, _pb, abil) => Math.max(1, Math.floor((abil.cha - 10) / 2)),
    resetOn: 'long',
    description: 'Bonus action: expend dice from your pool (max 5 at once) to heal a creature you can see within 60 ft by 1d6 per die. Pool = 1 + Warlock level d6s.',
  },
  {
    id: 'dark-ones-own-luck',
    name: "Dark One's Own Luck",
    class: 'Warlock',
    subclass: 'The Fiend',
    minLevel: 6,
    maxUses: () => 1,
    resetOn: 'short',
    description: 'When you make an ability check or saving throw, add 1d10 to the roll.',
  },
  {
    id: 'entropic-ward',
    name: 'Entropic Ward',
    class: 'Warlock',
    subclass: 'The Great Old One',
    minLevel: 6,
    maxUses: () => 1,
    resetOn: 'short',
    description: 'Reaction: when a creature attacks you, impose disadvantage on that roll. If it misses, gain advantage on your next attack against it this turn.',
  },
  {
    id: 'form-of-dread',
    name: 'Form of Dread',
    class: 'Warlock',
    subclass: 'The Undead',
    minLevel: 1,
    maxUses: (_lvl, pb) => pb,
    resetOn: 'long',
    description: 'Bonus action: transform for 1 minute. Immunity to fright, frighten creatures on hit (WIS save), become undead type.',
  },

  // ── Wizard subclasses ──────────────────────────────────────────────────────
  {
    id: 'bladesong',
    name: 'Bladesong',
    class: 'Wizard',
    subclass: 'Bladesinging',
    minLevel: 2,
    maxUses: (_lvl, _pb, abil) => Math.max(1, Math.floor((abil.int - 10) / 2)),
    resetOn: 'short',
    description: 'Bonus action: enter a bladesong for 1 minute. +INT to AC, +10 speed, advantage on Acrobatics, +INT to concentration saves.',
  },
  {
    id: 'momentary-stasis',
    name: 'Momentary Stasis',
    class: 'Wizard',
    subclass: 'Chronurgy Magic',
    minLevel: 6,
    maxUses: (_lvl, _pb, abil) => Math.max(1, Math.floor((abil.int - 10) / 2)),
    resetOn: 'long',
    description: 'Action: force a Large or smaller creature within 60 ft to succeed on a CON save or be incapacitated and its speed is 0 until end of your next turn.',
  },
  {
    id: 'violent-attraction',
    name: 'Violent Attraction',
    class: 'Wizard',
    subclass: 'Graviturgy Magic',
    minLevel: 10,
    maxUses: (_lvl, _pb, abil) => Math.max(1, Math.floor((abil.int - 10) / 2)),
    resetOn: 'long',
    description: 'Reaction: when a creature within 60 ft hits with a weapon attack or takes a fall, add 1d10 to the damage dealt.',
  },
  {
    id: 'illusory-self',
    name: 'Illusory Self',
    class: 'Wizard',
    subclass: 'School of Illusion',
    minLevel: 10,
    maxUses: () => 1,
    resetOn: 'short',
    description: 'Reaction: when a creature attacks you, create an illusory duplicate to intercept — the attack automatically misses.',
  },
  {
    id: 'the-third-eye',
    name: 'The Third Eye',
    class: 'Wizard',
    subclass: 'School of Divination',
    minLevel: 10,
    maxUses: () => 1,
    resetOn: 'short',
    description: 'Action: gain one of these until your next long rest — Darkvision 60 ft, Ethereal Sight 60 ft, see invisible creatures, or read any language.',
  },
];

/**
 * Compute which actions a character has based on their classes, levels, and feats.
 * Returns ComputedAction[] with current uses loaded from storedActionUses.
 */
export function computeActions(
  classes: StoredChar['classes'],
  feats: StoredChar['feats'],
  abilityScores: StoredChar['abilityScores'],
  pb: number,
  storedActionUses: Record<string, number> | undefined,
): ComputedAction[] {
  const result: ComputedAction[] = [];

  for (const def of ACTION_DEFS) {
    let max = 0;
    let className = def.class;

    if (def.class === null && def.feat) {
      // Feat-granted ability — check primary name and any aliases
      const allNames = [def.feat, ...(def.featAliases ?? [])];
      if (!allNames.some(n => feats.includes(n))) continue;
      max = def.maxUses(0, pb, abilityScores);
    } else if (def.class) {
      // Class-granted ability
      const cls = classes.find(c => c.name === def.class);
      if (!cls || cls.level < def.minLevel) continue;
      // Subclass filter
      if (def.subclass && cls.subclass !== def.subclass) continue;
      max = def.maxUses(cls.level, pb, abilityScores);
    } else {
      continue;
    }

    if (max <= 0) continue;

    const current = storedActionUses?.[def.id] ?? max;

    result.push({
      id: def.id,
      name: def.name,
      current,
      max,
      resetOn: def.resetOn,
      description: def.description,
      className,
      hpPool: def.hpPool,
    });
  }

  return result;
}
